services:
  app:
    build:
      context: .
      dockerfile: ./Docker-compose-file
    container_name: simple-python-server-fastapi
    command: uvicorn fastapi-main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 8080:80
    volumes:
      - ..:/app